version: '3.3'

services:

  x2go-mate:
    image: "vpetcu1/x2go-mate-${PROJECT}:${TAG}"
    container_name: "x2go-mate-${PROJECT}"
    restart: always
    ports:
      - "23:22"
      - "4502:4502"
    volumes:
      - "./${PROJECT}/:/home/desktop/${PROJECT}/"
      - /var/run/docker.sock:/var/run/docker.sock
    shm_size: '2gb'
    privileged: true
