version: '3.3'

services:

  mysql:
    image: mysql:5.7
    container_name: "mysql-${PROJECT}"
    volumes:
      - ../x2go-mate-full-bekaert-deslee/mysql/data/:/var/lib/mysql
      - ../x2go-mate-full-bekaert-deslee/mysql/configuration/conf.d:/etc/mysql/conf.d
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: myrootsql!
      MYSQL_ROOT_HOST: '%'
      MYSQL_DATABASE: bekaertdesleelr
      MYSQL_USER: bekaertdesleelr
      MYSQL_PASSWORD: youcanthandle!thetruth
    ports:
      - "3306:3306"

  ldme-mate-base:
    image: "vpetcu1/ldme-mate-base:${TAG}"
    container_name: "${PROJECT}"
    restart: always
    hostname: ${PROJECT}
    environment:
    - PASSWORD=password
    - USER=desktop
    cap_add:
    - SYS_PTRACE
    stdin_open: true
    tty: true
    ports:
      - "24:22"
      - "4004:4000/tcp"
    volumes:
      - "/etc/timezone:/etc/timezone:ro"
      - "/etc/localtime:/etc/localtime:ro"
      - "../x2go-mate-full-bekaert-deslee/${PROJECT}/:/home/desktop/${PROJECT}/"
      - /var/run/docker.sock:/var/run/docker.sock
#      - "home:/home/desktop"
      - "./home/:/home/desktop"
    shm_size: '2gb'
    privileged: true
    links: 
      - "mysql:database"
