version: '3.3'

services:

  mysql:
    image: mysql:5.7
    container_name: "mysql-${PROJECT}"
    volumes:
      - ./mysql/data/:/var/lib/mysql
      - ./mysql/configuration/conf.d:/etc/mysql/conf.d
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: myrootsql!
      MYSQL_ROOT_HOST: '%'
      MYSQL_DATABASE: bekaertdesleelr
      MYSQL_USER: bekaertdesleelr
      MYSQL_PASSWORD: youcanthandle!thetruth
    ports:
      - "3306:3306"

  x2go-mate:
    image: "vpetcu1/x2go-mate-${PROJECT}:${TAG}"
    container_name: "x2go-mate-${PROJECT}"
    restart: always
    ports:
      - "23:22"
      - "8080:8080"
    volumes:
      - "./${PROJECT}/:/home/desktop/${PROJECT}/"
      - /var/run/docker.sock:/var/run/docker.sock
    shm_size: '2gb'
    privileged: true
    links: 
      - "mysql:database"
