version: '3.3'

services:

  ubuntu-headless:
    image: "vpetcu1/ubuntu-headless:${TAG}"
    container_name: "ubuntu-headless-${PROJECT}"
    restart: always
    ports:
      - "23:22"
      - "4502:4502"
      - "80:80"
      - "3000:3000"
    volumes:
      - "./${PROJECT}/:/home/desktop/${PROJECT}/"
      - /var/run/docker.sock:/var/run/docker.sock
#      - "home:/home/desktop"
      - "./home/:/home/desktop"
    shm_size: '2gb'
    privileged: true
