version: '3.3'

services:

  x2go-mate:
    image: "vpetcu1/ubuntu-headless:${TAG}"
    container_name: "ubuntu-headless-${PROJECT}"
    restart: always
    ports:
      - "24:22"
      - "4503:4502"
      - "81:80"
      - "4001:4000"
    volumes:
#      - "./${PROJECT}/:/home/desktop/${PROJECT}/"
      - /var/run/docker.sock:/var/run/docker.sock
#      - "home:/home/desktop"
#      - "./home/:/home/desktop"
    shm_size: '2gb'
    privileged: true

volumes:
  home: