version: '3.3'

services:

  x2go-mate:
    image: "vpetcu1/ubuntu-mate-base:${TAG}"
    container_name: "${PROJECT}"
    restart: always
    hostname: ${PROJECT}
    environment:
    - PASSWORD=password
    - USER=desktop
    cap_add:
    - SYS_PTRACE
    stdin_open: true
    tty: true
    ports:
      - "25:22"
      - "4005:4000/tcp"
    volumes:
      - /run/snapd.socket:/run/snapd.socket
#      - "./${PROJECT}/:/home/desktop/${PROJECT}/"
      - /var/run/docker.sock:/var/run/docker.sock
#      - "home:/home/desktop"
#      - "./home/:/home/desktop"
    shm_size: '2gb'
    privileged: true
